# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
# Opt out of sending fastlane usage metrics

@app_name = 'tst-872a6ef8-f9d5-4bc-170-id'
@base_name = 'tst_872a6ef8_f9d5_4bc_170'
@filename = "#{@base_name}.xcodeproj"
@workspace_name = "#{@base_name}.xcworkspace"
@identifier = "com.crowdbotics.#{@app_name}"
@app_privacy_details = "app_privacy_details.json"

import_from_git(
  url: "git@github.com:crowdbotics/fastlane-config.git", # The URL of the repository to import the Fastfile from.
  branch: "#{ENV.fetch('FASTLANE_CONFIG_VERSION', "master")}", # The branch to checkout on the repository.
  path: "ios/Fastfile", # The path of the Fastfile in the repository.
)
